version: "3"
services:
  sql_shenanigans:
    build: .
    ports:
      - 9090:80
    container_name: sql_shenanigans
    restart: always
    depends_on: 
      - database
    # volumes:
    #   - ./src:/var/www/html

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vault
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - database
    
  
